### ISSUE TITLE
Bind ResourceManager "tcpip" to specific IP Address

### ISSUE THREAD

**Issue by yekscorp** [pyvisa/pyvisa#248] opened 2016-12-05 17:01 UTC
Is there a way to bind the ResourceManager class object to a specific IP address when attempting to open a socket? I have multiple network cards and unless I enable them in the correct order, pyvisa tries to connect using the wrong subnet and throws an exception.

The code I am calling to connect is the following:

`self.rm = visa.ResourceManager()`
`self.tester = self.rm.open_resource(u'TCPIP::%s::%s::INSTR' % (address, port))`

**Comment by MatthieuDartiailh** [comment] 2020-09-06 21:49
The proper way is probably to specify the card index after TCPIP (see the documentation about resource names). Closing given how old the issue is.

**Closed by MatthieuDartiailh** 2020-09-06 21:49 UTC
