### ISSUE TITLE
Python 3.11.4 interpreter seems to cause resource manager to produce an empty list.

### ISSUE THREAD

**Issue by ZachLSantos** [pyvisa/pyvisa#763] opened 2023-08-07 16:46 UTC
Python 3.11.4 interpreter seems to cause resource manager to produce an empty list with no devices, but using a 3.11.3 interpreter still functions normally. I've only ever interfaced with GPIB devices, so issue could be specific to GPIB.

Using 3.11.4:
--------------
```python
rm = pyvisa.ResourceManager()
rm.list_resources()
```
>```python
>()
>```

Using 3.11.3:
--------------
```python
rm = pyvisa.ResourceManager()
rm.list_resources()
```
>```python
>('GPIB0::11::INSTR', 'GPIB0::18::INSTR')
>```

**Output of `pyvisa-info`**
--------------

Machine Details:
   Platform ID:    Windows-10-10.0.19044-SP0
   Processor:      Intel64 Family 6 Model 154 Stepping 4, GenuineIntel       

Python:
   Implementation: CPython
   Executable:     C:\Users\user\Documents\Python\.venv\Scripts\python.exe
   Version:        3.11.4
   Compiler:       MSC v.1934 64 bit (AMD64)
   Bits:           64bit
   Build:          Jun  7 2023 05:45:37 (#tags/v3.11.4:d2340ef)
   Unicode:        UCS4

PyVISA Version: 1.13.0

Backends:
   ivi:
      Version: 1.13.0 (bundled with PyVISA)
      #1: C:\Windows\system32\visa32.dll:
         found by: auto
         bitness: 64
         Vendor: National Instruments
         Impl. Version: 24118016
         Spec. Version: 7340032
      #2: C:\Windows\system32\visa64.dll:
         found by: auto
         bitness: 64
         Vendor: National Instruments
         Impl. Version: 24118016
         Spec. Version: 7340032

**Comment by MatthieuDartiailh** [comment] 2023-08-08 09:09
That's a truly weird one. Do you have both Python installed side by side ? if so could you post the output of `pyvisa-info` with python 3.11.3.
Also do you see the instruments using NI MAX (just to be sure).

**Comment by ZachLSantos** [comment] 2023-08-08 17:15
I cannot.

The following code works fine using 3.11.3:
```python
import pyvisa
rm = pyvisa.ResourceManager()
sa = rm.open_resource('GPIB0::11::INSTR')
```
but produces the following error when using 3.11.4:
```
VisaIOError: VI_ERROR_INTF_NUM_NCONFIG (-1073807195): The interface type is valid but the specified interface number is not configured.
```

**Comment by ZachLSantos** [comment] 2023-09-15 18:53
This problem seems to persist in the new python update (3.11.5) as well.

**Comment by ZachLSantos** [comment] 2023-09-15 18:54
This problem seems to persist in the new python update (3.11.5) as well.

**Comment by ZachLSantos** [comment] 2023-09-15 18:55
This problem seems to persist in the new python update (3.11.5) as well.

**Comment by MatthieuDartiailh** [comment] 2023-09-16 12:51
Thanks for the updated report. Do you see the same issue with other resources than GPIB ones ? (It would be easier for me to investigate locally). Using Keysight, you should be able to manually add a TCPIP resource even if it does not exist and it should then be listed.

I went through 3.11.4 changelog but did not see anything, so I may have to bisect manually, but to do that, I need to be able to reproduce the issue.

**Comment by MatthieuDartiailh** [comment] 2023-09-18 15:23
This is extremely weird. At the level at which we interact with VISA, there should be no differences between resources !

Could you edit pyvisa/ctwrapper/functions.py and add a bunch of prints in `_find_resources` and `_find_next`. I am in particular interested in the returned values from the call to the dll.

**Comment by ZachLSantos** [comment] 2023-09-19 13:38
I still have a pretty novice understanding when it comes to python and programming in general, so my apologies for not completely comprehending, but you're saying that I should add print statements into these functions, and then try and connect to the GPIB instrument again right? Where exactly would I add the print statements in this case for it to be beneficial?

**Comment by MatthieuDartiailh** [comment] 2023-09-20 09:59
I tried to reproduce on a setup on which I do have GPIB devices and failed. The only difference is that I am running Keysight instead of NI. Here is the output I managed to get:
```
(py3113) C:\Users\manip.batm>python
Python 3.11.3 | packaged by Anaconda, Inc. | (main, May 15 2023, 15:41:31) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvisa
>>> rm = pyvisa.ResourceManager()
>>> rm.list_resources()
('GPIB0::17::INSTR', 'GPIB0::18::INSTR')
>>> quit()

(py3113) C:\Users\manip.batm>conda activate py3115

(py3115) C:\Users\manip.batm>python
Python 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvisa
>>> rm = pyvisa.ResourceManager()
>>> rm.list_resources()
('GPIB0::17::INSTR', 'GPIB0::18::INSTR')
```

And the output of pyvisa-info for 3.11.3 and 5:
```
Machine Details:
   Platform ID:    Windows-10-10.0.19045-SP0
   Processor:      Intel64 Family 6 Model 158 Stepping 13, GenuineIntel

Python:
   Implementation: CPython
   Executable:     C:\Anaconda3\envs\py3113\python.exe
   Version:        3.11.3
   Compiler:       MSC v.1916 64 bit (AMD64)
   Bits:           64bit
   Build:          May 15 2023 15:41:31 (#main)
   Unicode:        UCS4

PyVISA Version: 1.13.0

Backends:
   ivi:
      Version: 1.13.0 (bundled with PyVISA)
      #1: C:\WINDOWS\system32\visa32.dll:
         found by: auto
         bitness: 64
         Vendor: Keysight Technologies
         Impl. Version: 1378253280
         Spec. Version: 7340288
      #2: C:\WINDOWS\system32\visa64.dll:
         found by: auto
         bitness: 64
         Vendor: Keysight Technologies
         Impl. Version: 1378253280
         Spec. Version: 7340288
```

```Machine Details:
   Platform ID:    Windows-10-10.0.19045-SP0
   Processor:      Intel64 Family 6 Model 158 Stepping 13, GenuineIntel

Python:
   Implementation: CPython
   Executable:     C:\Anaconda3\envs\py3115\python.exe
   Version:        3.11.5
   Compiler:       MSC v.1916 64 bit (AMD64)
   Bits:           64bit
   Build:          Sep 11 2023 13:26:23 (#main)
   Unicode:        UCS4

PyVISA Version: 1.13.0

Backends:
   ivi:
      Version: 1.13.0 (bundled with PyVISA)
      #1: C:\WINDOWS\system32\visa32.dll:
         found by: auto
         bitness: 64
         Vendor: Keysight Technologies
         Impl. Version: 1378253280
         Spec. Version: 7340288
      #2: C:\WINDOWS\system32\visa64.dll:
         found by: auto
         bitness: 64
         Vendor: Keysight Technologies
         Impl. Version: 1378253280
         Spec. Version: 7340288
```

My next suggestion would be to try to re-install both Python and NI-VISA.

**Comment by MatthieuDartiailh** [comment] 2023-10-12 21:57
Closing since I cannot reproduce. @ZachLSantos feel free to re-open if you have more information

**Closed by MatthieuDartiailh** 2023-10-12 21:57 UTC
