### ISSUE TITLE
Pyvisa enabling  Over current and over voltage protection on a DC  electronic Load  (Chroma 6314A)

### ISSUE THREAD

**Issue by LydieNsangou** [pyvisa/pyvisa#620] opened 2021-08-06 13:27 UTC
hi everyone,
please can someone help me out?. i am trying to enable the over current and over voltage protection on my electronic load automatically with Pyvisa using python as programming language. i have checked already in the Manual but could not really get how to enable the over current and over voltage protection. 
if any one has already had to do with this, i will appreciate your help

kind regards

**Comment by LongnoseRob** [comment] 2021-08-07 13:43
If I read the manual pg. 39 (the only pulblic available, I could find was https://xdevs.com/doc/Chroma/63103a/CHROMA631xxSeries_um.pdf ) correctly, the over-current/-voltage protections set depeding on the output mouldes parameters.

According to my understanding these protections are **always active** to protect the modules.

The limits for the different protections are listed as part of the spectification table from page 15 of above linked PDF.

**Comment by LydieNsangou** [comment] 2021-08-09 08:50
@LongnoseRob  thanks very much for your response . you are actually right the over-current /- voltage Protection are active on the output modules. but your could also do an OCP/OPP Test to check if it properly works

**Comment by MatthieuDartiailh** [comment] 2021-08-09 09:42
Closing since it appears the issue is resolved

**Closed by MatthieuDartiailh** 2021-08-09 09:42 UTC
