### ISSUE TITLE
Pyinstaller packaged exe file can't find package pyvisa-py

### ISSUE THREAD

**Issue by mike9755** [pyvisa/pyvisa#479] opened 2019-12-02 14:02 UTC
(pip install pyvisa pyvisa-py)
      
import pyvisa
rm = pyvisa.ResourceManager('@py')

part of code as above, it works well with direct running *.py file, but it failed when package the *.py file to executable file with pyinstaller, the wrong message as below:
"ValueError: Wrapper not found: No package named pyvisa-py"
Does anybody meet same question with me or help to fix it, thank you very much
Wrong message and system info as below pictures:
![image](https://user-images.githubusercontent.com/5673534/69965483-54f28100-154f-11ea-9ed6-580ea2bf1865.png)
![image](https://user-images.githubusercontent.com/5673534/69965503-5f147f80-154f-11ea-94c1-9c88e9b9d086.png)

**Comment by MatthieuDartiailh** [comment] 2019-12-02 14:35
Closing as duplicate of https://github.com/pyvisa/pyvisa-py/issues/216

**Closed by MatthieuDartiailh** 2019-12-02 14:35 UTC
