### ISSUE TITLE
Delayed Read response from SR810 lockin amplifier over Prologix GPIB-USB

### ISSUE THREAD

**Issue by SinghNidhi** [pyvisa/pyvisa#201] opened 2015-12-28 07:35 UTC
Hi,
I am trying to read data from SR810 Lockin amplifier over Prologix GPIB-USB

Attached  is the screenshot of the shell showing commands and their response
![image](https://cloud.githubusercontent.com/assets/15606203/12015500/4f4a9b3c-ad63-11e5-9d40-0058262953b0.png)

As we can see, the response to the commands is extremely delayed even when the data points are updated on-time.
Also when I am querying something I am getting reply of the previous query for example as we can see in the above screenshot, I am getting a response '8191' to the query 'print(prologix.ask('SRAT?'))' which should ideally have given me '13' as a reply as shown in this screenshot
![image 1](https://cloud.githubusercontent.com/assets/15606203/12015516/97e1c7d0-ad63-11e5-93f0-25238544eb96.png)

What could be the probable reason of this delay?

**Comment by MatthieuDartiailh** [comment] 2018-02-25 19:03
Closing given that the issue is old, feel free to re-open if there is more to discuss.

**Closed by MatthieuDartiailh** 2018-02-25 19:03 UTC
